# Generated by Django 5.2.6 on 2025-09-27 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastros", "0010_cadastro_tipo_chave_pix_alter_cadastro_chave_pix"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cadastros", "Cadastros"),
                            ("efetivados", "Efetivados"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Importação",
                    ),
                ),
                (
                    "planilha",
                    models.FileField(
                        help_text="Arquivo CSV ou XLSX com os dados para importação",
                        upload_to="import_batches/%Y/%m/",
                        verbose_name="Planilha",
                    ),
                ),
                (
                    "anexos_zip",
                    models.FileField(
                        blank=True,
                        help_text="Arquivo ZIP com documentos organizados por CPF",
                        null=True,
                        upload_to="import_batches/%Y/%m/",
                        verbose_name="Anexos ZIP",
                    ),
                ),
                (
                    "mapping_json",
                    models.JSONField(
                        default=dict,
                        help_text="Mapeamento das colunas da planilha para campos do modelo",
                        verbose_name="Mapeamento JSON",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("dry_run", "Simulação"),
                            ("processing", "Processando"),
                            ("completed", "Concluído"),
                            ("error", "Erro"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total_linhas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de Linhas"
                    ),
                ),
                (
                    "linhas_processadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Linhas Processadas"
                    ),
                ),
                (
                    "linhas_sucesso",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Linhas com Sucesso"
                    ),
                ),
                (
                    "linhas_erro",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Linhas com Erro"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de Importação",
                "verbose_name_plural": "Lotes de Importação",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        help_text="Tipo identificado pelo nome do arquivo",
                        max_length=50,
                        verbose_name="Tipo do Documento",
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        upload_to="import_cadastros_docs/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "nome_original",
                    models.CharField(
                        help_text="Nome original do arquivo no ZIP",
                        max_length=255,
                        verbose_name="Nome Original",
                    ),
                ),
                (
                    "cpf_pasta",
                    models.CharField(
                        help_text="CPF da pasta onde o arquivo estava no ZIP",
                        max_length=11,
                        verbose_name="CPF da Pasta",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="importar_cadastros.importbatch",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "cadastro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_documents",
                        to="cadastros.cadastro",
                        verbose_name="Cadastro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Importado",
                "verbose_name_plural": "Documentos Importados",
                "ordering": ["cadastro", "tipo", "nome_original"],
            },
        ),
        migrations.CreateModel(
            name="ImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linha_numero",
                    models.PositiveIntegerField(verbose_name="Número da Linha"),
                ),
                (
                    "dados_brutos",
                    models.JSONField(
                        help_text="Dados originais da linha da planilha",
                        verbose_name="Dados Brutos",
                    ),
                ),
                ("sucesso", models.BooleanField(default=False, verbose_name="Sucesso")),
                (
                    "mensagem_erro",
                    models.TextField(
                        blank=True,
                        help_text="Detalhes do erro caso o processamento falhe",
                        verbose_name="Mensagem de Erro",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="importar_cadastros.importbatch",
                        verbose_name="Lote",
                    ),
                ),
                (
                    "cadastro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_rows",
                        to="cadastros.cadastro",
                        verbose_name="Cadastro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha de Importação",
                "verbose_name_plural": "Linhas de Importação",
                "ordering": ["linha_numero"],
                "unique_together": {("batch", "linha_numero")},
            },
        ),
    ]
