version: '3.8'

services:
  db:
    image: postgres:15
    container_name: abase_postgres
    environment:
      POSTGRES_DB: abase_db
      POSTGRES_USER: helcv
      POSTGRES_PASSWORD: abs123
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helcv -d abase_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    container_name: abase_web
    command: python start_abase.py
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://helcv:abs123@db:5432/abase_db
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: