# Generated by Django 5.1.3 on 2025-09-11 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoTesouraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição detalhada da movimentação', max_length=200, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da movimentação em reais', max_digits=10, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada de Recurso'), ('saida', 'Saída de Recurso')], max_length=10, verbose_name='Tipo de Movimentação')),
                ('data', models.DateField(verbose_name='Data da Movimentação')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre a movimentação', null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.ForeignKey(help_text='Usuário que registrou a movimentação', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Movimentação de Tesouraria',
                'verbose_name_plural': 'Movimentações de Tesouraria',
                'db_table': 'tesouraria_movimentacao',
                'ordering': ['-data', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
