# Generated by Django 5.1.3 on 2025-09-11 15:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0002_movimentacaotesouraria_delete_transacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competencia', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('cpf', models.CharField(max_length=14)),
                ('matricula', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('LIQUIDADA', 'Liquidada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_importacao', models.DateTimeField(auto_now_add=True)),
                ('data_liquidacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['-competencia', 'cpf'],
                'unique_together': {('competencia', 'cpf', 'matricula')},
            },
        ),
        migrations.CreateModel(
            name='ReconciliacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('total_processados', models.IntegerField(default=0)),
                ('total_conciliados', models.IntegerField(default=0)),
                ('detalhes', models.TextField(blank=True)),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Reconciliação',
                'verbose_name_plural': 'Logs de Reconciliação',
                'ordering': ['-data_execucao'],
            },
        ),
    ]
