# Generated by Django 5.1.3 on 2025-09-11 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cadastro_data_primeira_mensalidade_and_more'),
        ('tesouraria', '0003_mensalidade_reconciliacaolog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoTesouraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Processamento'), ('em_processamento', 'Em Processamento'), ('processado', 'Processado com Sucesso'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status do Processo')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada na Tesouraria')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Processamento')),
                ('observacoes_tesouraria', models.TextField(blank=True, help_text='Observações internas da tesouraria', verbose_name='Observações da Tesouraria')),
                ('cadastro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo_tesouraria', to='cadastros.cadastro', verbose_name='Cadastro')),
                ('processado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_tesouraria_processados', to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
            ],
            options={
                'verbose_name': 'Processo da Tesouraria',
                'verbose_name_plural': 'Processos da Tesouraria',
                'ordering': ['-data_entrada'],
            },
        ),
    ]
