# Generated by Django 5.2.6 on 2025-09-12 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
        ('tesouraria', '0004_processotesouraria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processotesouraria',
            name='agente_responsavel',
            field=models.ForeignKey(blank=True, help_text='Agente que fez o cadastro original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_tesouraria_agente', to=settings.AUTH_USER_MODEL, verbose_name='Agente Responsável'),
        ),
        migrations.AddField(
            model_name='processotesouraria',
            name='observacoes_analise',
            field=models.TextField(blank=True, help_text='Observações vindas do processo de análise', verbose_name='Observações da Análise'),
        ),
        migrations.AddField(
            model_name='processotesouraria',
            name='origem_analise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_tesouraria', to='analise.analiseprocesso', verbose_name='Origem da Análise'),
        ),
    ]
