# Generated by Django 5.2.6 on 2025-09-12 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0005_processotesouraria_agente_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processotesouraria',
            name='agente_responsavel',
            field=models.ForeignKey(
                blank=True,
                help_text='Agente que fez o cadastro original',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='processos_tesouraria_agente',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Agente Responsável'
            ),
        ),
    ]
