# Generated by Django 5.2.6 on 2025-09-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesouraria', '0006_auto_20250912_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='processotesouraria',
            name='comprovante_agente',
            field=models.FileField(blank=True, help_text='Comprovante do auxílio pago ao agente', null=True, upload_to='tesouraria/comprovantes/agentes/', verbose_name='Comprovante de Pagamento do Agente'),
        ),
        migrations.AddField(
            model_name='processotesouraria',
            name='comprovante_associado',
            field=models.FileField(blank=True, help_text='Comprovante do pagamento liberado para o associado', null=True, upload_to='tesouraria/comprovantes/associados/', verbose_name='Comprovante de Pagamento do Associado'),
        ),
    ]
