# Generated by Django 5.2.6 on 2025-09-17 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesouraria", "0007_processotesouraria_comprovante_agente_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processotesouraria",
            name="analista_origem",
            field=models.ForeignKey(
                blank=True,
                help_text="Analista que primeiro assumiu e aprovou este processo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processos_tesouraria_origem",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Analista de Origem",
            ),
        ),
        migrations.AddField(
            model_name="processotesouraria",
            name="data_aprovacao",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que o processo foi aprovado na análise",
                null=True,
                verbose_name="Data da Aprovação",
            ),
        ),
    ]
