# Generated by Django 4.2.24 on 2025-09-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesouraria", "0008_processotesouraria_analista_origem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processotesouraria",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente de Processamento"),
                    ("em_processamento", "Em Processamento"),
                    ("em_validacao_video", "Em Validação Vídeo"),
                    ("em_averbacao", "Em Averbação"),
                    ("processado", "Processado com Sucesso"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status do Processo",
            ),
        ),
    ]
