# Generated by Django 5.2.6 on 2025-09-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tesouraria", "0010_alter_processotesouraria_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processotesouraria",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendentes"),
                    ("em_processamento", "Em Processamento"),
                    ("em_validacao_video", "Validação Vídeo"),
                    ("em_averbacao", "Em Averbação"),
                    ("processado", "Processados"),
                    ("rejeitado", "Rejeitado"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status do Processo",
            ),
        ),
    ]
