# Generated by Django 5.1.3 on 2025-09-11 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_alter_cadastro_data_primeira_mensalidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('rejeitado', 'Rejeitado - Devolvido ao Agente'), ('suspenso', 'Suspenso - Aguardando Documentos')], default='pendente', max_length=20, verbose_name='Status da Análise')),
                ('tipo_analise', models.CharField(choices=[('documental', 'Análise Documental'), ('dados', 'Análise de Dados'), ('completa', 'Análise Completa')], default='completa', max_length=20, verbose_name='Tipo de Análise')),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=1, verbose_name='Prioridade')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada na Análise')),
                ('data_inicio_analise', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início da Análise')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('observacoes_analista', models.TextField(blank=True, help_text='Observações internas do analista durante a análise', verbose_name='Observações do Analista')),
                ('feedback_agente', models.TextField(blank=True, help_text='Feedback que será enviado ao agente em caso de rejeição', verbose_name='Feedback para o Agente')),
                ('prazo_analise', models.DateTimeField(blank=True, help_text='Prazo limite para conclusão da análise', null=True, verbose_name='Prazo para Análise')),
                ('analista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Analista Responsável')),
                ('cadastro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_processo', to='cadastros.cadastro', verbose_name='Cadastro')),
            ],
            options={
                'verbose_name': 'Processo de Análise',
                'verbose_name_plural': 'Processos de Análise',
                'ordering': ['-prioridade', 'data_entrada'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação Realizada')),
                ('status_anterior', models.CharField(blank=True, choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('rejeitado', 'Rejeitado - Devolvido ao Agente'), ('suspenso', 'Suspenso - Aguardando Documentos')], max_length=20, null=True, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(blank=True, choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('rejeitado', 'Rejeitado - Devolvido ao Agente'), ('suspenso', 'Suspenso - Aguardando Documentos')], max_length=20, null=True, verbose_name='Novo Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='analise.analiseprocesso', verbose_name='Processo de Análise')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Análise',
                'verbose_name_plural': 'Histórico de Análises',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, verbose_name='Item do Checklist')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre este item específico', verbose_name='Observações')),
                ('data_verificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Verificação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='analise.analiseprocesso', verbose_name='Processo de Análise')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
                'unique_together': {('processo', 'item')},
            },
        ),
    ]
