# Generated by Django 5.2.6 on 2025-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_add_correcao_feita_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseprocesso',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('rejeitado', 'Rejeitado - Devolvido ao Agente'), ('suspenso', 'Suspenso - Aguardando Documentos'), ('correcao_feita', 'Correção Feita - Aguardando Nova Análise'), ('cancelado', 'Cancelado Definitivamente')], default='pendente', max_length=20, verbose_name='Status da Análise'),
        ),
        migrations.AlterField(
            model_name='historicoanalise',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('rejeitado', 'Rejeitado - Devolvido ao Agente'), ('suspenso', 'Suspenso - Aguardando Documentos'), ('correcao_feita', 'Correção Feita - Aguardando Nova Análise'), ('cancelado', 'Cancelado Definitivamente')], max_length=20, null=True, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='historicoanalise',
            name='status_novo',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('rejeitado', 'Rejeitado - Devolvido ao Agente'), ('suspenso', 'Suspenso - Aguardando Documentos'), ('correcao_feita', 'Correção Feita - Aguardando Nova Análise'), ('cancelado', 'Cancelado Definitivamente')], max_length=20, null=True, verbose_name='Novo Status'),
        ),
    ]
