# Generated by Django 5.2.6 on 2025-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0004_alter_analiseprocesso_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseprocesso',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('correcao_feita', 'Correção Feita - Aguardando Nova Análise'), ('enviado_para_correcao', 'Enviado para Correção'), ('correcao_realizada', 'Correção Realizada'), ('cancelado', 'Cancelado Definitivamente')], default='pendente', max_length=25, verbose_name='Status da Análise'),
        ),
        migrations.AlterField(
            model_name='historicoanalise',
            name='status_anterior',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('correcao_feita', 'Correção Feita - Aguardando Nova Análise'), ('enviado_para_correcao', 'Enviado para Correção'), ('correcao_realizada', 'Correção Realizada'), ('cancelado', 'Cancelado Definitivamente')], max_length=25, null=True, verbose_name='Status Anterior'),
        ),
        migrations.AlterField(
            model_name='historicoanalise',
            name='status_novo',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente de Análise'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado - Encaminhado para Tesouraria'), ('correcao_feita', 'Correção Feita - Aguardando Nova Análise'), ('enviado_para_correcao', 'Enviado para Correção'), ('correcao_realizada', 'Correção Realizada'), ('cancelado', 'Cancelado Definitivamente')], max_length=25, null=True, verbose_name='Novo Status'),
        ),
    ]
