# Generated by Django 5.2.6 on 2025-09-12 02:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMAIL', 'Email'), ('SISTEMA', 'Sistema'), ('SMS', 'SMS')], default='EMAIL', max_length=20)),
                ('destinatarios', models.TextField(help_text='Lista de destinatários (emails separados por vírgula)')),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALHA', 'Falha'), ('DESABILITADO', 'Desabilitado')], default='DESABILITADO', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('erro', models.TextField(blank=True, help_text='Detalhes do erro, se houver', null=True)),
                ('contexto', models.CharField(blank=True, help_text='Contexto da notificação (ex: cadastro_status_change)', max_length=100)),
                ('usuario_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Notificação',
                'verbose_name_plural': 'Logs de Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
