# Generated by Django 5.2.6 on 2025-09-16 13:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROCESSO_ATRIBUIDO', 'Processo Atribuído'), ('PROCESSO_CORRIGIDO', 'Processo Corrigido'), ('PROCESSO_APROVADO', 'Processo Aprovado'), ('PROCESSO_REJEITADO', 'Processo Rejeitado'), ('CADASTRO_PENDENTE', 'Cadastro Pendente'), ('PAGAMENTO_LIBERADO', 'Pagamento Liberado'), ('SISTEMA', 'Sistema')], max_length=30)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('url_acao', models.URLField(blank=True, help_text='URL para ação relacionada', null=True)),
                ('objeto_id', models.PositiveIntegerField(blank=True, help_text='ID do objeto relacionado', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
