# Generated by Django 5.1.3 on 2025-09-11 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoImportacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='importacoes/')),
                ('tipo_arquivo', models.CharField(choices=[('CSV', 'CSV'), ('TXT', 'TXT')], max_length=10)),
                ('competencia', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=12)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('total_linhas', models.IntegerField(default=0)),
                ('linhas_processadas', models.IntegerField(default=0)),
                ('linhas_com_erro', models.IntegerField(default=0)),
                ('log_erros', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_upload'],
            },
        ),
    ]
