# Generated by Django 5.2.6 on 2025-09-15 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField(help_text='Primeiro dia do mês de referência (ex.: 2025-05-01)')),
                ('data_geracao', models.DateField(blank=True, null=True)),
                ('arquivo_nome', models.CharField(max_length=255)),
                ('arquivo_sha256', models.CharField(max_length=64, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('total_linhas', models.PositiveIntegerField(default=0)),
                ('total_processados', models.PositiveIntegerField(default=0)),
                ('total_atualizados', models.PositiveIntegerField(default=0)),
                ('total_ignorados', models.PositiveIntegerField(default=0)),
                ('total_nao_encontrados', models.PositiveIntegerField(default=0)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportacaoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('matricula', models.CharField(max_length=32)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('orgao_pagto', models.CharField(blank=True, max_length=32)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status_externo', models.CharField(max_length=2)),
                ('status_legenda', models.CharField(max_length=200)),
                ('acao', models.CharField(choices=[('MARCADA_LIQUIDADA', 'Parcela marcada como liquidada'), ('IGNORADA_STATUS', 'Linha ignorada pelo status externo'), ('CADASTRO_NAO_EFETIVADO', 'Cadastro não está efetivado'), ('CPF_MATRICULA_NAO_ENCONTRADO', 'Cadastro não encontrado por CPF+Matrícula'), ('PARCELA_DO_MES_NAO_ENCONTRADA', 'Não há parcela do mês de referência')], max_length=64)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastro_id', models.IntegerField(blank=True, null=True)),
                ('parcela_id', models.IntegerField(blank=True, null=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='importador.importacaocontribuicao')),
            ],
        ),
        migrations.DeleteModel(
            name='ArquivoImportacao',
        ),
    ]
