# Generated by Django 5.2.6 on 2025-09-11 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_cadastro_parcelaantecipacao_delete_pessoa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='data_primeira_mensalidade',
            field=models.DateField(blank=True, null=True, verbose_name='Data da primeira contribuição'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='disponivel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Repasse ao Associado (R$)'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='mensalidade_associativa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Contribuição Associativa (R$)'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='valor_total_antecipacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total das 3 Cotas (R$)'),
        ),
    ]
