# Generated by Django 5.2.6 on 2025-09-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_cadastro_data_primeira_mensalidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='matricula_servidor',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Matrícula do Servidor Público'),
        ),
    ]
