# Generated by Django 5.1.3 on 2025-09-12 11:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_cadastro_matricula_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='auxilio_agente_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Auxílio do Agente (R$)'),
        ),
    ]
