# Generated by Django 5.1.3 on 2025-09-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_cadastro_auxilio_agente_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='nome_razao_social',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome_completo',
            field=models.CharField(max_length=180, verbose_name='Nome Completo'),
        ),
    ]
