# Generated by Django 5.2.6 on 2025-09-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_remove_cadastro_nome_razao_social_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcelaantecipacao',
            options={'ordering': ['numero'], 'verbose_name': 'Mensalidade', 'verbose_name_plural': 'Mensalidades'},
        ),
    ]
