# Generated by Django 5.2.6 on 2025-09-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_update_parcela_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='situacao_servidor',
            field=models.CharField(blank=True, choices=[('ATIVO', 'Ativo'), ('EFETIVO', 'Efetivo'), ('COMISSIONADO', 'Comissionado'), ('APOSENTADO', 'Aposentado'), ('PENSIONISTA', 'Pensionista'), ('LICENCIADO', 'Licenciado'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Situação do Servidor'),
        ),
    ]
