# Generated by Django 5.2.6 on 2025-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_cadastro_situacao_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelaantecipacao',
            name='atualizado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelaantecipacao',
            name='status_origem_txt',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
