# Generated by Django 5.2.6 on 2025-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_parcelaantecipacao_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('TELEFONE', 'Telefone'), ('ALEATORIA', 'Chave Aleatória')], default='', max_length=10, verbose_name='Tipo de Chave PIX'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='chave_pix',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Chave Pix'),
        ),
    ]
