# Generated by Django 5.1.3 on 2025-09-11 12:54

import apps.documentos.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_cadastro_parcelaantecipacao_delete_pessoa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=32)),
                ('arquivo', models.FileField(storage=apps.documentos.storage.PrivateStorage(), upload_to='docs/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cadastros.cadastro')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoRascunho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_token', models.CharField(db_index=True, max_length=40)),
                ('tipo', models.CharField(max_length=32)),
                ('arquivo', models.FileField(storage=apps.documentos.storage.PrivateStorage(), upload_to='docs_draft/%Y/%m/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
