# Generated by Django 5.2.6 on 2025-09-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_securitylog_delete_logauditoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogAuditoria',
        ),
    ]
